### ISSUE TITLE
How to install on Joomla 5 ?

### ISSUE THREAD

**Issue by antotouv** [jbrailas/JMapMyLDAP_v5#1]
Hello,
Can you tell me how to install your extension on Joomla 5? I tried to drag and drop the files into the root of my Joomla site but it didn't work.
Thank you.

**Comment by billtzim** [comment]
@antotouv , what i did is to take the original zip installation files and replace the updated code files in the respective folders/zip files. You can find where everything goes if you follow the folder namings. 
After that i was able to install it in Joomla 5, although wasn't still able to make it work. Also some changes in code had to be made due to errors (some in files that existed in the original packages, not the updated ones)

if @jbrailas has any thoughts on that it would be great , he really did an awesome job!

**Comment by jbrailas** [comment]
You can use the zip files located inside the installation_files folder.
